### PR TITLE
adds possibility to add extension bundles to load in additional to ma...

### PR DESCRIPTION
**Pull request by sidorovis**
…in list, would be used in future for dynamically loaded bundles

This provide possibility to load additional list of bundles that could provide possibility to load dynamically bundles as "plugins" for Videobridge.

### CODE REVIEW

**Comment by sidorovis** [comment]
Ah, now it has https://github.com/jitsi/jitsi-android-osgi/pull/1 in dependency. :(
Probably it's better to separate last commit to another pull request. But if it is not a big problem to merge jitsi-android-osgi, it's easier to merge this feature together.

**Comment by sidorovis** [comment]
Do we have to update any pom.xml with new version of jitsi-android-osgi first or it is possible just to merge this pull request?

**Comment by bgrozev** [comment]
Let's do the pom.xml update as part of the next PR.

**Comment by sidorovis** [comment]
Actually there is no next PR. The last two things are:
 * update last release versions on jitsi-android-osgi, jicoco. 
 * update dependency versions of mentioned libraries at jitsi-videobridge.

**Comment by bgrozev** [comment]
> update last release versions on jitsi-android-osgi, jicoco.

A new version of jicoco was automatically pushed to the maven repo already:
https://github.com/jitsi/jitsi-maven-repository/commit/2a3b08e279cc20e732ab3ae7c5abc1ab73515d31

I will push jitsi-android-osgi. Do you need to update jicoco's pom.xml with the new version of jitsi-android-osgi?

**Comment by sidorovis** [comment]
That's depend on the way how this will get into jitsi-videobridge. 
If jitsi-videobridge will use new version of jitsi-android-osgi and new version of jicoco in close future - that's enough. 
But I believe it's better to update everything to the last version of both jitsi-android-osgi and jicoco.

**Comment by bgrozev** [comment]
We now have jitsi-android-osgi version 1.0-20180322.162617-2 in the maven repo

**Comment by bgrozev** [comment]
Yes, please. Can you also create one to update jicoco/pom.xml?

**Pull request merged**
