### PR TITLE
Influxdb upgrade

### PR DESCRIPTION
**Pull request by jmartine**
Added support for writing data points to InfluxDB 0.9+

### CODE REVIEW

**Comment by dwilson6** [comment]
Has someone had a chance to look at this?

**Comment by rdsmallwood928** [comment]
Any chance this could get merged?

**Comment by dwilson6** [comment]
@paweldomas, it looks like you were the one who wrote most of the code jmartine changed. Do you have any thoughts? Are there any other projects impacted by these changes?

**Comment by paweldomas** [comment]
Hi ! I will try to have a look during the weekend. If I don't please remind me again.

**Comment by spditner** [comment]
There is the web interface used to browse the logged statistics, jitsi/jiloin. It would probably need to be updated in order to be compatible with Influx 0.9

**Comment by jmartine** [comment]
I have opened up a pull request for the influxdb upgrade to jiloin here

https://github.com/jitsi/jiloin/pull/10https://github.com/jitsi/jiloin/pull/10

-- Justin

________________________________

**Comment by jmartine** [comment]
Hi Pawel,

did you ever get a chance to check this out?   I also added to pull request that upgrades jilion to use influx 0.9 as well.

Thanks!

-- Justin
________________________________

**Comment by paweldomas** [comment]
Hi ! Thanks for the PR, I will review then soon !

**Comment by paweldomas** [comment]
Hi ! Just wanted to let you know that I had a look at that yesterday evening and it looks good. Will merge it once I check https://github.com/jitsi/jiloin/pull/10

**Comment by jmartine** [comment]
Hi Pawel,

I noticed that you still haven't merged in this change.  Is there something I can do to help get it merged?

Thanks,
    Justin

________________________________

**Comment by paweldomas** [comment]
Sorry I completely forgot about it, will merge it later today !

**Comment by paweldomas** [comment]
jenkins: it's ok to test

**Comment by paweldomas** [comment]
@jmartine I feel a bit uncomfortable to merge this PR, as it will break room name queries in jiloin:
https://github.com/jitsi/jiloin/pull/10
Is it big effort to have that fixed ?
I also wonder if we're ever going to use jiloin and InfluxDB ? @emcho WDYT ?

**Comment by bgrozev** [comment]
I don't think we should worry about breaking jiloin at this point. It needs some work before it's in a usable state anyway.

**Comment by paweldomas** [comment]
That's true, I will merge it unless @emcho objects

**Pull request merged**
