### PR TITLE
Change POM dependency only to libjitsi, not jitsi-util.

### PR DESCRIPTION
**Pull request by JonathanLennox**

### CODE REVIEW

**Comment by bgrozev** [comment]
Damian, this already happens because the jitsi-desktop bundles specify a version of libjitsi. Or am I missing something?

**Comment by damencho** [comment]
Yeah, it is ... was just wondering about it as it further seemed to me to add more complexity to the graph of dependencies ... and was thinking of jicoco as a more low-level dependency ... yeah anyway, I just wanted to share my thoughts, not to block this PR and what you had planned...

**Comment by damencho** [comment]
I had a really great confusion!!! So ignore me! All-day I was thinking about jitsi-utils, where this is about jitsi-util :(

**Comment by bgrozev** [comment]
Yeah, replacing jitsi-utils with libjitsi would be weird haha :)

**Pull request merged**
